### ISSUE TITLE
Pyang validation fails

### ISSUE THREAD

**Issue by GregMirsky** [YangCatalog/bottle-yang-extractor-validator#10]
Noticed that today validation fails on YANG module that worked before:
ietf-stamp@2018-02-27.yang:9: error: module "ietf-inet-types" not found in search path
ietf-stamp@2018-02-27.yang:13: error: module "ietf-yang-types" not found in search path
ietf-stamp@2018-02-27.yang:17: error: module "ietf-key-chain" not found in search path
I've checked with BFD YANG and got similar failures:
Confdc Output
ietf-bfd-mpls@2018-01-22.yang:22: error: module 'ietf-routing' not found
ietf-bfd-types@2018-01-22.yang:23: error: module 'ietf-routing' not found
ietf-bfd-types@2018-01-22.yang:28: error: module 'ietf-key-chain' not found
ietf-bfd@2018-01-22.yang:13: error: module 'ietf-routing' not found
yanglint Validation
yanglint error: Unable to use search path (/var/tmp/yangmodules/extracted) - No such file or directory.

**Comment by cmoberg** [comment]
Hi Greg,

 Are you using the hosted version on yangvalidator.org or a local install?

**Comment by miroslavKovacPantheon** [comment]
closing for no answer as invalid

**Comment by Maconair** [comment]
Hello everyone,
I'd like to ask if a solution was found for this issue.
I'm facing the same problem and I'm using a local install for the confdc
