### ISSUE TITLE
YANG validation does not produce any report

### ISSUE THREAD

**Issue by GregMirsky** [YangCatalog/bottle-yang-extractor-validator#11]
[Fetch, extract , and validate ](http://www.yangvalidator.com/) doesn't produce any output when Upload Internet Draft option used.
Appreciate your suggestions and help.

Regards,
Greg

**Comment by miroslavKovacPantheon** [comment]
The same question as in #12

**Comment by miroslavKovacPantheon** [comment]
Closing as duplicate of #12 and invalid for no answer
