### ISSUE TITLE
No output when parsing uploaded draft.

### ISSUE THREAD

**Issue by GregMirsky** [YangCatalog/bottle-yang-extractor-validator#12]
YANGvalidator doesn't produce any output when I upload my working version of the YANG model in IETF draft. Appreciate your help.

Regards,
Greg

**Comment by miroslavKovacPantheon** [comment]
The same question in here. A year ago it was not managed by us. I believe this should not be a problem any more. I have tested several files myself. Could you confirm? I leave this open  for another month just to be sure from your side that there is not some special file causing some problems. If no response by then closing it as invalid.

Thank you

**Comment by miroslavKovacPantheon** [comment]
closing as invalid
