### ISSUE TITLE
AttributeError: module 'pip' has no attribute 'locations'

### ISSUE THREAD

**Issue by lemikev** [YangCatalog/bottle-yang-extractor-validator#13]
The Pyang Validation section return the error:

Traceback (most recent call last):
pyang", line 444, in 
    run()
pyang", line 219, in run
    repos = pyang.FileRepository(path, no_path_recurse=o.no_path_recurse)
__init__.py", line 408, in __init__
    location = pip.locations.distutils_scheme('pyang')
AttributeError: 'module' object has no attribute 'locations'

To fix the same problem on my own version of pyang, I have commented out the following section in __init__.py.

'''
import pkgutil
if not pkgutil.find_loader('pip'):
    return  # abort search if pip is not installed

import pip
location = pip.locations.distutils_scheme('pyang')
self.dirs.append(os.path.join(location['data'],
                              'share','yang','modules'))
'''

**Comment by miroslavKovacPantheon** [comment]
This is not an issue any more

**Comment by ftianf** [comment]
I have got same issue and have to comment those lines out. @miroslavKovacPantheon What did you do to fix the problem?

**Comment by miroslavKovacPantheon** [comment]
@ftianf this project was update using Django and different version of pyang. This bug was not directly from this project but from pyang module instead. So once the project got updated this bug was invalid for our project.

Anyway I did some digging and found what they did. It seems that there is a problem with different versions of pip. What pip version are you using? Here is the code what they did although it s more of a heck then correct fix:

```
            # hack below to handle pip 10 internals
            # if someone knows pip and how to fix this, it would be great!
            location = None
            try:
                import pip.locations as locations
                location = locations.distutils_scheme('pyang')
            except:
                try:
                    import pip._internal.locations as locations
                    location = locations.distutils_scheme('pyang')
                except:
                    pass
            if location is not None:
                self.dirs.append(os.path.join(location['data'],
                                              'share','yang','modules'))
```
