### ISSUE TITLE
YANG validation fails

### ISSUE THREAD

**Issue by GregMirsky** [YangCatalog/bottle-yang-extractor-validator#14]
Previously fine models fail with the following:
Traceback (most recent call last):
pyang", line 444, in <module>
    run()
pyang", line 219, in run
    repos = pyang.FileRepository(path, no_path_recurse=o.no_path_recurse)
__init__.py", line 408, in __init__
    location = pip.locations.distutils_scheme('pyang')
AttributeError: 'module' object has no attribute 'locations'
Much appreciate your help.

Regards,
Greg

**Comment by miroslavKovacPantheon** [comment]
Hi Greg.. sorry for late response.. but thir repository was recently moved to IETF owner. I would like to ask if this is still valid issue and if yes could you provide the name of the modules that fail? I would like to try and check them myself.

Thank you

**Comment by miroslavKovacPantheon** [comment]
Closing for no response as invalid. modules seemes to validate fine.
