### ISSUE TITLE
YANG model tree diagram is not working

### ISSUE THREAD

**Issue by pkolesni** [YangCatalog/bottle-yang-extractor-validator#149]
Hi,

YANG [Module Details View](https://www.yangcatalog.org/yang-search/module_details) doesn't show Tree View for any module I've tried.

 This api works fine -> https://yangcatalog.org/api/services/tree/@.yang

Cheers, Pavel

**Comment by bclaise** [comment]
Pantheon, please solve that one ASAP.

Regards, Benoit

**Comment by rjsparks** [comment]
I think this is an environment variable not being set correctly.
See
https://github.com/search?q=repo%3AYangCatalog%2Ffrontend+MATOMO_TRACKER_URL&type=code

**Comment by microamp** [comment]
Fixed via https://github.com/YangCatalog/backend/pull/816. Please re-open the issue otherwise.
