### ISSUE TITLE
https://www.yangcatalog.org/yangvalidator/ => yumaworks

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/bottle-yang-extractor-validator#19]
https://www.yangcatalog.org/yangvalidator/
I see pyang, confdc. yanglint. We need yumaworks as well.
On top of that, we need the same output as the compilation-result in the metadata.
That means: we need pyang --ietf

**Comment by miroslavKovacPantheon** [comment]
This is resolved

**Comment by miroslavKovacPantheon** [comment]
pyang --ietf is in there if the module is ietf same goes for bbf ieee mef...

yumaworks in progress
