### ISSUE TITLE
xym extraction errors

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/bottle-yang-extractor-validator#20]
Need to get the xym extraction errors in
    1. tracker => xym error
    2. yangcatalog.org/yangvalidator.and yangvalidator.org

ex: 
![Capture1](https://user-images.githubusercontent.com/6932412/61584424-647bab00-ab15-11e9-82f2-edd17631353f.JPG)

These errors are available at temp_runIETFstats.txt

**Comment by miroslavKovacPantheon** [comment]
Closing this issue since we have xym extraction errors in yangvalidator already. this was added earlier in mid of 2019
