### ISSUE TITLE
combine yangvalidator and yangcatalog issue tracker

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/bottle-yang-extractor-validator#26]
Now that the yangvalidator is under yangcatalog, add a  "yangvalidator" entry under https://github.com/YangCatalog
It should point to https://github.com/YangCatalog/bottle-yang-extractor-validator/issues (this comes from https://yangvalidator.com/yangvalidator/about)

**Comment by miroslavKovacPantheon** [comment]
This has been fixed
