### ISSUE TITLE
Cannot extract modules from draft-ietf-lpwan-schc-yang-data-model-02

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/bottle-yang-extractor-validator#27]
It seems that no YANG modules can be extracted from draft-ietf-lpwan-schc-yang-data-model-02.

**Comment by miroslavKovacPantheon** [comment]
This seems to be a xym problem. I ll take a look

**Comment by miroslavKovacPantheon** [comment]
This is a problem of draft itself https://tools.ietf.org/html/draft-ietf-lpwan-schc-yang-data-model-02 has following line
`<code begins> file schc-id@2020-02-28.yang`
it contains file between code beings and actual file. Making it not valid.

**Comment by miroslavKovacPantheon** [comment]
I am closing this issue since this needs to be fixed on the draft side
