### ISSUE TITLE
Rest API for uploaded YANG modules

### ISSUE THREAD

**Issue by BalazsLengyel** [YangCatalog/bottle-yang-extractor-validator#39]
Is it possible to upload a set of zipped yang modules using the rest API and get them validated ?
What is the first part of the URL
https://www.yangvalidator.com/yangvalidator/rest 
or
https://www.yangvalidator.com/yangvalidator

Thanks Balazs

**Comment by miroslavKovacPantheon** [comment]
This API is CSRF procted and therefore browser is required. This is for security reasons.

The response would come in HTML format anyway so parsing that would be probably a nightmare .

regards,
Miroslav Kovac

**Comment by BalazsLengyel** [comment]
IMHO the reason for the REST API is to allow automation. It would be nice to use it for uploaded files too.
I understand there are issues.
I don't understand the CSRF part, as in the browser, there is no login or authentication.

Anyways thanks for the answer.

**Comment by miroslavKovacPantheon** [comment]
We will be rebuilding the whole UI so I ll take this into consideration for that as well. Should be done like in late February with new release.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

after release of the new YANG Catalog UI functionality of uploading set of zipped yang modules using the rest API is available.
Feel free to check it here: https://yangcatalog.org/yangvalidator
API Documentation: https://yangcatalog.org/yangvalidator/api

Regards,
Slavomir Mazur
