### ISSUE TITLE
Imports not resolved in a zipped yang module set

### ISSUE THREAD

**Issue by BalazsLengyel** [YangCatalog/bottle-yang-extractor-validator#40]
I uploaded a zipped set of yang files that depend on each other (import each other). However imports between the uploaded files were not resolved. I got a lot of error messages like:

err : Importing "_3gpp-common-measurements" module into "_3gpp-common-managed-function" failed.

 Is it possible to solve this? How?

**Comment by miroslavKovacPantheon** [comment]
Thank you for reporting this.

Could you provide these modules or are they proprietary?

If not would you be able to copy paste at least the output that you have received?

regards,
Miroslav Kovac

**Comment by BalazsLengyel** [comment]
[rel-16-yams@2020-11-16.zip](https://github.com/YangCatalog/bottle-yang-extractor-validator/files/5546480/rel-16-yams%402020-11-16.zip)

This is a set of 3GPP YANG modules.

**Comment by miroslavKovacPantheon** [comment]
Ok I have identified the problem. It seems like we are not getting dependencies for confd. But this is only true for modules that are unknown for yangcatalog. Fix is on its way.

Thank you

**Comment by miroslavKovacPantheon** [comment]
this is resolved [here](https://github.com/YangCatalog/bottle-yang-extractor-validator/pull/41#pullrequestreview-535399789)

It will be in production code in next release

**Comment by BalazsLengyel** [comment]
Thanks, Balazs
