### ISSUE TITLE
Can't access extracted file

### ISSUE THREAD

**Issue by gilesheron** [YangCatalog/bottle-yang-extractor-validator#7]
when I click on the file listed under "Extracted 1 YANG modules" I just get taken to the same page I'm already on...

**Comment by cmoberg** [comment]
Old issue, BUT: the link from "Extracted <n> YANG modules" leads to the section of the page related to that file, not to the extracted file itself. Should it?

**Comment by miroslavKovacPantheon** [comment]
This is not an issue. This will only show what is the compilation status of that file and not file itself. For this you can use [yangcatalog module details](https://www.yangcatalog.org/yang-search/module_details). type in the module and click the "schema" link.
