### ISSUE TITLE
errors on augments

### ISSUE THREAD

**Issue by samans** [YangCatalog/bottle-yang-extractor-validator#74]
The online yangvalidator throws errors on augments.  Taken separately the augment statement validates, but when both augment statements are included in the same file, the validator chokes on them.  

I have created four test yang files.  Two of them validate in the online validator and two do not.

The test-ok.yang and test-ok-2.yang files work.

The test-ok file has only one augment (for /nw:networks/nw:network/nw:network-types/tet:te-topology)
The test-ok-2.yang file has only one augment (for /nw:networks/nw:network/nw:node/nt:termination-point/tet:te)
Taken separately they augments work.

The test-1.yang file has both augments  Taken together, the online yanglint spits out:
```
libyang err : Augment target node "/nw:networks/nw:network/nw:network-types/tet:te-topology" from module "test-1" was not found. (/test-1:{augment='/nw:networks/nw:network/nw:network-types/tet:te-topology'})
libyang err : Augment target node "/nw:networks/nw:network/nw:node/nt:termination-point/tet:te" from module "test-1" was not found. (/test-1:{augment='/nw:networks/nw:network/nw:node/nt:termination-point/tet:te'})
YANGLINT[E]: Processing schema module from /var/yang/tmp/yangvalidator/yangvalidator-v2-workdir-BYiAZxUm/test-1.yang failed.
```

When I swap the order of the augments, I get different errors – which is strange. (test-2.yang)
```
libyang err : Augment target node "/nw:networks/nw:network/nw:node/te/te-node-attributes/connectivity-matrices/connectivity-matrix" from module "ietf-te-topology" was not found. (/ietf-te-topology:{augment='/nw:networks/nw:network/nw:node/te/te-node-attributes/connectivity-matrices/connectivity-matrix'})
libyang err : Augment target node "/nw:networks/nw:network/nw:node/te/tunnel-termination-point/local-link-connectivities" from module "ietf-te-topology" was not found. (/ietf-te-topology:{augment='/nw:networks/nw:network/nw:node/te/tunnel-termination-point/local-link-connectivities'})
libyang err : Augment target node "/nw:networks/nw:network/nw:node" from module "ietf-te-topology" was not found. (/ietf-te-topology:{augment='/nw:networks/nw:network/nw:node'})
libyang err : Augment target node "/nw:networks/nw:network/nw:node/te/information-source-entry/connectivity-matrices/connectivity-matrix" from module "ietf-te-topology" was not found. (/ietf-te-topology:{augment='/nw:networks/nw:network/nw:node/te/information-source-entry/connectivity-matrices/connectivity-matrix'})
YANGLINT[E]: Processing schema module from /var/yang/tmp/yangvalidator/yangvalidator-v2-workdir-fXryozgz/test-2.yang failed.
```
I have also attached the the full module that I'm trying to validate (ietf-microwave-topology@2021-09-27.yang)

BTW... I have yanglint v1 and yanglint v2 running locally in linux and all the yang files I have shared validate (and I have instance data that works too)
[augtest.zip](https://github.com/YangCatalog/bottle-yang-extractor-validator/files/7237342/augtest.zip)
.

thanks

**Comment by SlavomirMazurPantheon** [comment]
Hello,

first of all, on what version of libyang did you try this and which command did you use?
I tried to validate all the modules you shared with us using console and got the same results as online tool is displaying. I also tried it with different revisions of imported yang modules and also different versions of yanglint (2.0.88, 2.0.7, 2.0.0).
I used the following command:
```
yanglint -i -p /var/yang/tmp/yangvalidator/yangvalidator-v2-workdir-cIMiaTkm /var/yang/tmp/yangvalidator/yangvalidator-v2-workdir-cIMiaTkm/ietf-microwave-topology@2021-09-27.yang
```

Very interesting/strange thing is also that the errors are different whe you swap the order of the augments as you mentioned.
However, I asume that the error may be in the libyang tool itself.

Regards,
Slavomir Mazur

**Comment by samans** [comment]
I use yanglint 2.0.88 on ubuntu and do not see the error, I also have tried
1.10.7.  So, why the online tool doesn't work is a mystery.
I even tried running the online tool uploading all the yang files and got
the same result.

Here is a tar file of all the yang files needed and an expect script and an
instance file.  If there isn't a tar file attached, let me know and I can
try sending a zip or gz file.

When I run this I get the output found in the mw.out file in the tar file.

The fact that the online tool works when the augments are isolated and not
when they are together is odd as well.

If it would help to have a short online meeting for me to demonstrate,
please let me know.

regards,
-scott.

**Comment by samans** [comment]
Since the tar file didn't come through here is a zip file

[mw-test.zip](https://github.com/YangCatalog/bottle-yang-extractor-validator/files/7252095/mw-test.zip)

**Comment by SlavomirMazurPantheon** [comment]
Hello,

I tried to replicate your steps and I got the same result as you. However, there is no way to force the yangvalidator to load files in a particular order currently and we wont going to implement something like that. We still think this should be handled by yanglint itself. Yanglint should also keep eye on the order of files.

I am moving this issue to [libyang](https://github.com/CESNET/libyang)

**Comment by samans** [comment]
yanglint works if the files are ordered, so I will make sure all our
developers/testers know how to do that.  If a "yanglint *.yang" is done on
all the files, I get a validation error that is different from what the
online yangvalidator reports.  But at least we have a way forward.

Since I haven't found a way for the online yangvalidator to validate, I
will tell our developer/testers not to use the online yangvalidator.

If a small example would be helpful, I can create one.

regards,
-scott.
-scott.
