### ISSUE TITLE
schema preferences

### ISSUE THREAD

**Issue by rkrejci** [YangCatalog/bottle-yang-extractor-validator#9]
Hi,
how the yangvalidator is supposed to handle imports? I guess that yangvalidator have some internal storage where validators search for imported modules, but what if user submit also one of the imported modules? Should the submitted schema be prefered to the schema in the storage? What if the version in storage is newer and import is without revision? And what if the revision of the submitted schema is not specified in the filename?

Specific example:
- storage contains ietf-routing@2016-11-03.yang
- user submit files ietf-routing.yang and ietf-ipv4-unicast-routing.yang, revisons are not specified but revision of ietf-routing.yang is newer than 2016-11-03 and ietf-ipv4-unicast-routing imports ietf-routing without revision (so the newer)
- when the tools validate ietf-ipv4-unicast-routing and resolving ietf-routing import, are they supposed to
  - get revision just from the filename and suppose that if one ietf-routing has revision in filename, other ietf-routing without revision in filename simply does not have any revision (so user is supposed to submit correctly named files)?
  - parse all the ietf-routing files to get know the newest revision?
  - parse all accessible files (because ietf-routing.yang can be also named e.g. mySuperSchema.txt) to get the newest ietf-routing revision?

**Comment by cmoberg** [comment]
Radek,

 As always with you, that are all awesome questions and I have frankly not really thought this through really well. Any thoughts or ideas on how to move this forward?

**Comment by miroslavKovacPantheon** [comment]
I would create an option here to choose revision of imported module since it is not mandatory in yang file. If one chooses a revision that file will be used in validation otherwise it will validate using all the files it has accessible

**Comment by SlavomirMazurPantheon** [comment]
Hello,

after release of the new YANG Catalog UI functionality of choosing specific module revision is available.
Feel free to check it here: https://yangcatalog.org/yangvalidator
API Documentation: https://yangcatalog.org/yangvalidator/api

Regards,
Slavomir Mazur
